# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOS
        pod 'IQKeyboardManagerSwift'
        pod 'SVProgressHUD'
        pod 'EVReflection/Alamofire'
        pod 'Kingfisher'
        pod 'FloatRatingView'
        pod 'DropDown'
        pod 'GoogleMaps'
        pod 'GooglePlaces'
        pod 'OTPTextField'
        pod 'Firebase/Messaging'
        pod 'Firebase/Analytics'
        pod 'Firebase/Crashlytics'
        pod 'SnapKit'
end
