# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsPaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsPaper

    pod 'IQKeyboardManagerSwift'
    pod 'SVProgressHUD'
    pod 'EVReflection/Alamofire'
    pod 'DateScrollPicker'
    pod 'DropDown'
    pod 'SROTPView'
    pod 'Firebase/Messaging'
  target 'NewsPaperTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'NewsPaperUITests' do
    # Pods for testing
  end

end
