
import Foundation


enum popUpMessage : String {
    case someWrong          = "Something went wrong. Please try again later"
    case emptyString        = "Please fill in all the fields"
    case emptyFullName      = "Please enter your full name"
    case emptyPassword      = "Please enter a password"
    case emptyCountry       = "Please select country name"
    case orginasitionEmpty  = "Please select organisation"
    case PasswordValid      = "Password must be between 6 and 16 characters"
    case UserValid          = "Username must be between 3 and 15 characters"
    case PasswrordValid     = "Please enter atleast one digit and one special character for your password in new password"
    case EmailValid         = "Please enter a valid email"
    case PhoneValid         = "Please enter a valid mobile number"
    case AlreadyExistsUser  = "This username is already registered"
    case emptyEmailId       = "Please enter your email"
    case emptyUserName      = "Please enter your username"
    case ConPassword        = "Please ensure password and confirmation password match"
    case currentPass        = "Please enter a valid password"
    case ValidPasscode      = "Please enter a valid PIN"
    case emptyGroupName     = "Please enter a group name"
    case AtLeastOneSelect   = "Please select atleast one member for the group"
    case DeleteAcc          = "Are you sure you want to delete this account?"
    case EmptyCurrentPass   = "Please enter your current password"
    case EmptyNewPass       = "Please enter a new password"
    case EmptyConfirmPass   = "Please confirm the new password"
    case NoInternet         = "The system is currently experiencing networking issues"
    case EmptyTag           = "Please enter atleast one tag or select a location"
    case DeleteChannel      = "Are you sure you want to delete the group?"
    case LeaveGroup         = "Are you sure you want to leave the group?"
    case DeleteMedia        = "Are you sure you want to delete this photo / video?"
    case mDeleteMedia       = "Are you sure you want to delete the selected photos / videos?"
    case clearNotif         = "Are you sure you want to clear all notifications?"
    case FirstTagMessage    = "Enter multiple tags separated by a comma (,)"
    case AdminDeletePhoto   = "Delete this picture permanently?\nThis picture will be deleted for all members as well"
    case AdminDeleteVideo   = "Delete this video permanently?\nThis video will be deleted for all members as well"
    case userDeletePhoto    = "Delete this picture permanently?"
    case userDeleteVideo    = "Delete this video permanently?"
    case DeleteCaseGroup    = "Group can only be deleted if there are no active members"
    case FileNotExistinAWS  = "Video file is no longer exist in the cloud"
    case largeVideoFile     = "Video duration should not exceed 30 seconds."
    case logoutStr          = "Are you sure you want to Logout?"
}

