# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CargoXpress' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CargoXpress

        pod 'IQKeyboardManagerSwift'
        pod 'SVProgressHUD'
        pod 'EVReflection/Alamofire'
        pod 'GMStepper'
        pod 'FloatRatingView'
        pod 'DropDown'
        pod 'Kingfisher'
        pod 'Firebase/Analytics'
        pod 'Firebase/Messaging'
        pod 'GooglePlaces'
        pod 'Charts'
end
